# Generated by Django 5.2.7 on 2025-11-04 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectrecord',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='collectrecord',
            name='return_date',
        ),
        migrations.AddField(
            model_name='collectrecord',
            name='collect_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
